# coding: utf-8

"""
    Cold Reach API

    API for Cold Reach email outreach platform

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from openapi_server.apis.default_api import router as DefaultApiRouter

app = FastAPI(
    title="Cold Reach API",
    description="API for Cold Reach email outreach platform",
    version="1.0.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:3000"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(DefaultApiRouter)
