# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class EmailTemplate(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    EmailTemplate - a model defined in OpenAPI

        id: The id of this EmailTemplate [Optional].
        name: The name of this EmailTemplate [Optional].
        subject: The subject of this EmailTemplate.
        body: The body of this EmailTemplate.
    """

    id: Optional[str] = Field(alias="id", default=None)
    name: Optional[str] = Field(alias="name", default=None)
    subject: str = Field(alias="subject")
    body: str = Field(alias="body")

EmailTemplate.update_forward_refs()
