# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.client import Client


class ImportClientsExcel200Response(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ImportClientsExcel200Response - a model defined in OpenAPI

        count: The count of this ImportClientsExcel200Response [Optional].
        clients: The clients of this ImportClientsExcel200Response [Optional].
    """

    count: Optional[int] = Field(alias="count", default=None)
    clients: Optional[List[Client]] = Field(alias="clients", default=None)

ImportClientsExcel200Response.update_forward_refs()
