# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class SendEmail200Response(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    SendEmail200Response - a model defined in OpenAPI

        success: The success of this SendEmail200Response [Optional].
        sent_count: The sent_count of this SendEmail200Response [Optional].
    """

    success: Optional[bool] = Field(alias="success", default=None)
    sent_count: Optional[int] = Field(alias="sent_count", default=None)

SendEmail200Response.update_forward_refs()
