# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class Template(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Template - a model defined in OpenAPI

        id: The id of this Template [Optional].
        name: The name of this Template.
        subject: The subject of this Template.
        body: The body of this Template.
    """

    id: Optional[str] = Field(alias="id", default=None)
    name: str = Field(alias="name")
    subject: str = Field(alias="subject")
    body: str = Field(alias="body")

    class Config:
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return str(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        import json
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Template:
        """Create an instance of Template from a JSON string"""
        import json
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> Template:
        """Create an instance of Template from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return Template.parse_obj(obj)

        _obj = Template.parse_obj({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "subject": obj.get("subject"),
            "body": obj.get("body")
        })
        return _obj
